In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df= pd.read_csv('/content/heart_disease_dataset.csv')
df

Age  Gender  Cholesterol  Blood Pressure  Heart Rate  Smoking  \
0     75  Female          228             119          66  Current   
1     48    Male          204             165          62  Current   
2     53    Male          234              91          67    Never   
3     69  Female          192              90          72  Current   
4     62  Female          172             163          93    Never   
..   ...     ...          ...             ...         ...      ...   
995   56  Female          269             111          86    Never   
996   78  Female          334             145          76    Never   
997   79    Male          151             179          81    Never   
998   60  Female          326             151          68   Former   
999   53    Male          226             116          82  Current   

    Alcohol Intake  Exercise Hours Family History Diabetes Obesity  \
0            Heavy               1             No       No     Yes   
1              NaN               5             No       No      No   
2            Heavy               3            Yes       No     Yes   
3              NaN               4             No      Yes      No   
4              NaN               6             No      Yes      No   
..             ...             ...            ...      ...     ...   
995          Heavy               5             No      Yes     Yes   
996            NaN               6             No       No      No   
997       Moderate               4            Yes       No     Yes   
998            NaN               8            Yes      Yes      No   
999            NaN               6             No       No     Yes   

     Stress Level  Blood Sugar Exercise Induced Angina   Chest Pain Type  \
0               8          119                     Yes   Atypical Angina   
1               9           70                     Yes    Typical Angina   
2               5          196                     Yes   Atypical Angina   
3               7          107                     Yes  Non-anginal Pain   
4               2          183                     Yes      Asymptomatic   
..            ...          ...                     ...               ...   
995            10          120                      No  Non-anginal Pain   
996            10          196                     Yes    Typical Angina   
997             8          189                     Yes      Asymptomatic   
998             5          174                     Yes   Atypical Angina   
999             5          161                     Yes      Asymptomatic   

     Heart Disease  
0                1  
1                0  
2                1  
3                0  
4                0  
..             ...  
995              1  
996              1  
997              0  
998              1  
999              1  

[1000 rows x 16 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype 
---  ------                   --------------  ----- 
 0   Age                      1000 non-null   int64 
 1   Gender                   1000 non-null   object
 2   Cholesterol              1000 non-null   int64 
 3   Blood Pressure           1000 non-null   int64 
 4   Heart Rate               1000 non-null   int64 
 5   Smoking                  1000 non-null   object
 6   Alcohol Intake           660 non-null    object
 7   Exercise Hours           1000 non-null   int64 
 8   Family History           1000 non-null   object
 9   Diabetes                 1000 non-null   object
 10  Obesity                  1000 non-null   object
 11  Stress Level             1000 non-null   int64 
 12  Blood Sugar              1000 non-null   int64 
 13  Exercise Induced Angina  1000 non-null   object
 14  Chest Pain Type          1000 non-null   

In [ ]:
df.dropna(inplace=True)

In [ ]:
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
Index: 660 entries, 0 to 997
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype 
---  ------                   --------------  ----- 
 0   Age                      660 non-null    int64 
 1   Gender                   660 non-null    object
 2   Cholesterol              660 non-null    int64 
 3   Blood Pressure           660 non-null    int64 
 4   Heart Rate               660 non-null    int64 
 5   Smoking                  660 non-null    object
 6   Alcohol Intake           660 non-null    object
 7   Exercise Hours           660 non-null    int64 
 8   Family History           660 non-null    object
 9   Diabetes                 660 non-null    object
 10  Obesity                  660 non-null    object
 11  Stress Level             660 non-null    int64 
 12  Blood Sugar              660 non-null    int64 
 13  Exercise Induced Angina  660 non-null    object
 14  Chest Pain Type          660 non-null    object

Age                        0
Gender                     0
Cholesterol                0
Blood Pressure             0
Heart Rate                 0
Smoking                    0
Alcohol Intake             0
Exercise Hours             0
Family History             0
Diabetes                   0
Obesity                    0
Stress Level               0
Blood Sugar                0
Exercise Induced Angina    0
Chest Pain Type            0
Heart Disease              0
dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder
le= LabelEncoder()
# df['Gender']= le.fit_transform(df['Gender'])
# df['ChestPainType']= le.fit_transform(df['Chest Pain Type'])
# df['Smoking']= le.fit_transform(df['Smoking'])
# df['Alcohol Intake']= le.fit_transform(df['Alcohol Intake'])
# df['Diabetes']= le.fit_transform(df['Diabetes'])
# df['Obesity']= le.fit_transform(df['Obesity'])
# df['Family History']= le.fit_transform(df['Family History'])
# df['Exercise Induced Angina']= le.fit_transform(df['Exercise Induced Angina'])
df[['Gender', 'Chest Pain Type', 'Smoking', 'Alcohol Intake','Diabetes','Obesity','Family History','Exercise Induced Angina']] = df[['Gender', 'Chest Pain Type', 'Smoking', 'Alcohol Intake','Diabetes','Obesity','Family History','Exercise Induced Angina']].apply(LabelEncoder().fit_transform)
df

Age  Gender  Cholesterol  Blood Pressure  Heart Rate  Smoking  \
0     75       0          228             119          66        0   
2     53       1          234              91          67        2   
6     64       0          211             105          86        1   
7     60       0          208             148          83        2   
8     37       0          317             137          66        0   
..   ...     ...          ...             ...         ...      ...   
991   26       0          215             100          74        2   
992   28       0          220             102          73        0   
994   52       1          248             159          76        1   
995   56       0          269             111          86        2   
997   79       1          151             179          81        2   

     Alcohol Intake  Exercise Hours  Family History  Diabetes  Obesity  \
0                 0               1               0         0        1   
2                 0               3               1         0        1   
6                 0               8               1         1        1   
7                 1               4               0         1        1   
8                 0               3               0         1        1   
..              ...             ...             ...       ...      ...   
991               0               7               0         1        0   
992               1               7               1         1        1   
994               1               9               0         1        1   
995               0               5               0         1        1   
997               1               4               1         0        1   

     Stress Level  Blood Sugar  Exercise Induced Angina  Chest Pain Type  \
0               8          119                        1                1   
2               5          196                        1                1   
6               2          120                        0                3   
7               2          113                        1                0   
8               5          114                        0                2   
..            ...          ...                      ...              ...   
991            10          135                        0                1   
992            10          102                        0                3   
994             2          152                        1                0   
995            10          120                        0                2   
997             8          189                        1                0   

     Heart Disease  
0                1  
2                1  
6                1  
7                1  
8                0  
..             ...  
991              0  
992              0  
994              1  
995              1  
997              0  

[660 rows x 16 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 660 entries, 0 to 997
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Age                      660 non-null    int64
 1   Gender                   660 non-null    int64
 2   Cholesterol              660 non-null    int64
 3   Blood Pressure           660 non-null    int64
 4   Heart Rate               660 non-null    int64
 5   Smoking                  660 non-null    int64
 6   Alcohol Intake           660 non-null    int64
 7   Exercise Hours           660 non-null    int64
 8   Family History           660 non-null    int64
 9   Diabetes                 660 non-null    int64
 10  Obesity                  660 non-null    int64
 11  Stress Level             660 non-null    int64
 12  Blood Sugar              660 non-null    int64
 13  Exercise Induced Angina  660 non-null    int64
 14  Chest Pain Type          660 non-null    int64
 15  Heart Disea

In [ ]:
df.corr()

Age    Gender  Cholesterol  Blood Pressure  \
Age                      1.000000  0.004848     0.007875        0.004500   
Gender                   0.004848  1.000000    -0.025584       -0.075573   
Cholesterol              0.007875 -0.025584     1.000000        0.027309   
Blood Pressure           0.004500 -0.075573     0.027309        1.000000   
Heart Rate               0.050212  0.022431    -0.010819       -0.006665   
Smoking                 -0.042466 -0.018998     0.012810        0.015343   
Alcohol Intake           0.093875 -0.012976     0.053458       -0.011483   
Exercise Hours          -0.007590 -0.039730     0.008885       -0.011361   
Family History           0.010722  0.094037    -0.036683       -0.000513   
Diabetes                -0.031614 -0.051294    -0.068161       -0.065743   
Obesity                  0.002003 -0.075548     0.015841       -0.043429   
Stress Level            -0.086295  0.034863     0.115721        0.018005   
Blood Sugar             -0.040666  0.053840    -0.004058       -0.092608   
Exercise Induced Angina -0.019522  0.013292     0.035075        0.024771   
Chest Pain Type         -0.024976 -0.001107    -0.106206        0.006195   
Heart Disease            0.648068  0.031281     0.369807        0.021624   

                         Heart Rate   Smoking  Alcohol Intake  Exercise Hours  \
Age                        0.050212 -0.042466        0.093875       -0.007590   
Gender                     0.022431 -0.018998       -0.012976       -0.039730   
Cholesterol               -0.010819  0.012810        0.053458        0.008885   
Blood Pressure            -0.006665  0.015343       -0.011483       -0.011361   
Heart Rate                 1.000000 -0.039496        0.002137       -0.006712   
Smoking                   -0.039496  1.000000        0.004237       -0.014182   
Alcohol Intake             0.002137  0.004237        1.000000        0.005267   
Exercise Hours            -0.006712 -0.014182        0.005267        1.000000   
Family History             0.060931 -0.011084       -0.036406        0.081056   
Diabetes                   0.028336  0.055490       -0.000294       -0.003190   
Obesity                   -0.030638 -0.033948        0.036228       -0.006643   
Stress Level              -0.030095  0.021193        0.002336        0.019318   
Blood Sugar                0.023769 -0.040360        0.008206       -0.010864   
Exercise Induced Angina    0.037545  0.008432        0.001662        0.068374   
Chest Pain Type            0.003958 -0.027963        0.024101        0.040182   
Heart Disease              0.040874 -0.012769        0.076589       -0.005986   

                         Family History  Diabetes   Obesity  Stress Level  \
Age                            0.010722 -0.031614  0.002003     -0.086295   
Gender                         0.094037 -0.051294 -0.075548      0.034863   
Cholesterol                   -0.036683 -0.068161  0.015841      0.115721   
Blood Pressure                -0.000513 -0.065743 -0.043429      0.018005   
Heart Rate                     0.060931  0.028336 -0.030638     -0.030095   
Smoking                       -0.011084  0.055490 -0.033948      0.021193   
Alcohol Intake                -0.036406 -0.000294  0.036228      0.002336   
Exercise Hours                 0.081056 -0.003190 -0.006643      0.019318   
Family History                 1.000000  0.018182  0.021247      0.060672   
Diabetes                       0.018182  1.000000 -0.014827     -0.074409   
Obesity                        0.021247 -0.014827  1.000000      0.029056   
Stress Level                   0.060672 -0.074409  0.029056      1.000000   
Blood Sugar                   -0.060053 -0.010502 -0.041366      0.002514   
Exercise Induced Angina       -0.006086 -0.055327  0.014409     -0.009019   
Chest Pain Type                0.008112  0.054046  0.047708     -0.000518   
Heart Disease                 -0.006194  0.017305  0.002839     -0.032253   

                         Blood Sugar  Exercise In

In [ ]:
d= df.drop(['Exercise Hours','Smoking','Family History','Stress Level','Chest Pain Type','Blood Sugar'], axis=1)
d

Age  Gender  Cholesterol  Blood Pressure  Heart Rate  Alcohol Intake  \
0     75       0          228             119          66               0   
2     53       1          234              91          67               0   
6     64       0          211             105          86               0   
7     60       0          208             148          83               1   
8     37       0          317             137          66               0   
..   ...     ...          ...             ...         ...             ...   
991   26       0          215             100          74               0   
992   28       0          220             102          73               1   
994   52       1          248             159          76               1   
995   56       0          269             111          86               0   
997   79       1          151             179          81               1   

     Diabetes  Obesity  Exercise Induced Angina  Heart Disease  
0           0        1                        1              1  
2           0        1                        1              1  
6           1        1                        0              1  
7           1        1                        1              1  
8           1        1                        0              0  
..        ...      ...                      ...            ...  
991         1        0                        0              0  
992         1        1                        0              0  
994         1        1                        1              1  
995         1        1                        0              1  
997         0        1                        1              0  

[660 rows x 10 columns]

In [ ]:
d.corr()

Age    Gender  Cholesterol  Blood Pressure  \
Age                      1.000000  0.004848     0.007875        0.004500   
Gender                   0.004848  1.000000    -0.025584       -0.075573   
Cholesterol              0.007875 -0.025584     1.000000        0.027309   
Blood Pressure           0.004500 -0.075573     0.027309        1.000000   
Heart Rate               0.050212  0.022431    -0.010819       -0.006665   
Alcohol Intake           0.093875 -0.012976     0.053458       -0.011483   
Diabetes                -0.031614 -0.051294    -0.068161       -0.065743   
Obesity                  0.002003 -0.075548     0.015841       -0.043429   
Exercise Induced Angina -0.019522  0.013292     0.035075        0.024771   
Heart Disease            0.648068  0.031281     0.369807        0.021624   

                         Heart Rate  Alcohol Intake  Diabetes   Obesity  \
Age                        0.050212        0.093875 -0.031614  0.002003   
Gender                     0.022431       -0.012976 -0.051294 -0.075548   
Cholesterol               -0.010819        0.053458 -0.068161  0.015841   
Blood Pressure            -0.006665       -0.011483 -0.065743 -0.043429   
Heart Rate                 1.000000        0.002137  0.028336 -0.030638   
Alcohol Intake             0.002137        1.000000 -0.000294  0.036228   
Diabetes                   0.028336       -0.000294  1.000000 -0.014827   
Obesity                   -0.030638        0.036228 -0.014827  1.000000   
Exercise Induced Angina    0.037545        0.001662 -0.055327  0.014409   
Heart Disease              0.040874        0.076589  0.017305  0.002839   

                         Exercise Induced Angina  Heart Disease  
Age                                    -0.019522       0.648068  
Gender                                  0.013292       0.031281  
Cholesterol                             0.035075       0.369807  
Blood Pressure                          0.024771       0.021624  
Heart Rate                              0.037545       0.040874  
Alcohol Intake                          0.001662       0.076589  
Diabetes                               -0.055327       0.017305  
Obesity                                 0.014409       0.002839  
Exercise Induced Angina                 1.000000       0.005654  
Heart Disease                           0.005654       1.000000

In [ ]:
X= d.iloc[:,:-1].values
X

array([[ 75,   0, 228, ...,   0,   1,   1],
       [ 53,   1, 234, ...,   0,   1,   1],
       [ 64,   0, 211, ...,   1,   1,   0],
       ...,
       [ 52,   1, 248, ...,   1,   1,   1],
       [ 56,   0, 269, ...,   1,   1,   0],
       [ 79,   1, 151, ...,   0,   1,   1]])

In [ ]:
y= d.iloc[:,-1].values
y

array([1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,

In [ ]:
d.isnull().sum()

Age                        0
Gender                     0
Cholesterol                0
Blood Pressure             0
Heart Rate                 0
Alcohol Intake             0
Diabetes                   0
Obesity                    0
Exercise Induced Angina    0
Heart Disease              0
dtype: int64

#Logistic Regression

#Splitting dataset into Train Set and Test Set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [ ]:
print(y_test)

[0 0 1 0 0 0 1 0 0 0 1 1 0 1 1 0 1 0 0 1 0 1 1 0 1 1 1 0 0 0 0 1 0 0 0 1 0
 0 0 1 1 0 0 0 0 0 0 1 1 0 1 1 0 0 0 1 1 0 0 0 1 1 1 1 0 0 0 0 1 1 1 0 0 1
 1 0 1 0 1 1 1 0 0 0 0 0 1 1 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 1 0
 0 0 1 1 0 1 0 0 0 0 0 0 0 1 0 0 1 1 0 0 0]


In [ ]:
X_train[0:5]

array([[ 52,   1, 319, 123,  96,   0,   0,   1,   0],
       [ 56,   1, 274, 105,  79,   1,   0,   1,   0],
       [ 57,   0, 229, 179,  63,   0,   1,   0,   0],
       [ 26,   0, 298, 162,  67,   1,   1,   1,   0],
       [ 63,   0, 302, 134,  98,   0,   1,   1,   0]])

#Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
X_train[0:5]

array([[-0.04759104,  0.96647087,  1.20049844, -0.49780124,  1.40690015,
        -0.94830405, -1.00379508,  0.95553309, -0.89901011],
       [ 0.20751626,  0.96647087,  0.4292294 , -1.1862621 , -0.0675115 ,
         1.05451411, -1.00379508,  0.95553309, -0.89901011],
       [ 0.27129309, -1.03469234, -0.34203964,  1.64407697, -1.45519304,
        -0.94830405,  0.99621927, -1.04653624, -0.89901011],
       [-1.70578851, -1.03469234,  0.84057289,  0.99386394, -1.10827266,
         1.05451411,  0.99621927,  0.95553309, -0.89901011],
       [ 0.65395404, -1.03469234,  0.90913013, -0.07707516,  1.58036034,
        -0.94830405,  0.99621927,  0.95553309, -0.89901011]])

In [ ]:
print(X_test)

[[-1.38690438 -1.03469234 -0.39345758 ...  0.99621927 -1.04653624
  -0.89901011]
 [-0.87668977 -1.03469234 -0.83907969 ...  0.99621927  0.95553309
  -0.89901011]
 [ 1.35549912 -1.03469234  0.84057289 ...  0.99621927  0.95553309
   1.11233454]
 ...
 [-0.23892152  0.96647087  1.32047362 ...  0.99621927  0.95553309
  -0.89901011]
 [-1.38690438  0.96647087  1.61184193 ... -1.00379508  0.95553309
   1.11233454]
 [ 0.78150769 -1.03469234 -1.33611974 ...  0.99621927  0.95553309
  -0.89901011]]


#Training Logistic Regression model on training set

In [ ]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

#Predict Test results

In [ ]:
y_pred= classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [0 0]]


#Making Confusion Metrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[78  5]
 [ 9 40]]


0.8939393939393939

#KNN model

In [ ]:
X

array([[ 75,   0, 228, ...,   0,   1,   1],
       [ 53,   1, 234, ...,   0,   1,   1],
       [ 64,   0, 211, ...,   1,   1,   0],
       ...,
       [ 52,   1, 248, ...,   1,   1,   1],
       [ 56,   0, 269, ...,   1,   1,   0],
       [ 79,   1, 151, ...,   0,   1,   1]])

In [ ]:
y

array([1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [ ]:
X_train

array([[ 52,   1, 319, ...,   0,   1,   0],
       [ 56,   1, 274, ...,   0,   1,   0],
       [ 57,   0, 229, ...,   1,   0,   0],
       ...,
       [ 67,   0, 244, ...,   1,   1,   0],
       [ 45,   0, 157, ...,   1,   0,   0],
       [ 44,   0, 297, ...,   0,   0,   1]])

In [ ]:
y_train

array([1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,

In [ ]:
X_test

array([[ 31,   0, 226, ...,   1,   0,   0],
       [ 39,   0, 200, ...,   1,   1,   0],
       [ 74,   0, 298, ...,   1,   1,   1],
       ...,
       [ 49,   1, 326, ...,   1,   1,   0],
       [ 31,   1, 343, ...,   0,   1,   1],
       [ 65,   0, 171, ...,   1,   1,   0]])

In [ ]:
y_test

array([0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0])

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
X_train

array([[-0.04759104,  0.96647087,  1.20049844, ..., -1.00379508,
         0.95553309, -0.89901011],
       [ 0.20751626,  0.96647087,  0.4292294 , ..., -1.00379508,
         0.95553309, -0.89901011],
       [ 0.27129309, -1.03469234, -0.34203964, ...,  0.99621927,
        -1.04653624, -0.89901011],
       ...,
       [ 0.90906134, -1.03469234, -0.08494996, ...,  0.99621927,
         0.95553309, -0.89901011],
       [-0.49402882, -1.03469234, -1.57607011, ...,  0.99621927,
        -1.04653624, -0.89901011],
       [-0.55780565, -1.03469234,  0.82343357, ..., -1.00379508,
        -1.04653624,  1.11233454]])

In [ ]:
X_test

array([[-1.38690438, -1.03469234, -0.39345758, ...,  0.99621927,
        -1.04653624, -0.89901011],
       [-0.87668977, -1.03469234, -0.83907969, ...,  0.99621927,
         0.95553309, -0.89901011],
       [ 1.35549912, -1.03469234,  0.84057289, ...,  0.99621927,
         0.95553309,  1.11233454],
       ...,
       [-0.23892152,  0.96647087,  1.32047362, ...,  0.99621927,
         0.95553309, -0.89901011],
       [-1.38690438,  0.96647087,  1.61184193, ..., -1.00379508,
         0.95553309,  1.11233454],
       [ 0.78150769, -1.03469234, -1.33611974, ...,  0.99621927,
         0.95553309, -0.89901011]])

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 11, metric = 'euclidean')
classifier.fit(X_train, y_train)

KNeighborsClassifier(metric='euclidean', n_neighbors=11)

In [ ]:
y_pred= classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [0 0]]


#Making Confusion Metrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[77  6]
 [ 7 42]]


0.9015151515151515

#SVM Classifier Model

In [ ]:
X

array([[ 75,   0, 228, ...,   0,   1,   1],
       [ 53,   1, 234, ...,   0,   1,   1],
       [ 64,   0, 211, ...,   1,   1,   0],
       ...,
       [ 52,   1, 248, ...,   1,   1,   1],
       [ 56,   0, 269, ...,   1,   1,   0],
       [ 79,   1, 151, ...,   0,   1,   1]])

In [ ]:
y

array([1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,

#Splitting dataset into Train Set and Test Set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [ ]:
X_train

array([[ 52,   1, 319, ...,   0,   1,   0],
       [ 56,   1, 274, ...,   0,   1,   0],
       [ 57,   0, 229, ...,   1,   0,   0],
       ...,
       [ 67,   0, 244, ...,   1,   1,   0],
       [ 45,   0, 157, ...,   1,   0,   0],
       [ 44,   0, 297, ...,   0,   0,   1]])

In [ ]:
y_train

array([1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,

In [ ]:
X_test

array([[ 31,   0, 226, ...,   1,   0,   0],
       [ 39,   0, 200, ...,   1,   1,   0],
       [ 74,   0, 298, ...,   1,   1,   1],
       ...,
       [ 49,   1, 326, ...,   1,   1,   0],
       [ 31,   1, 343, ...,   0,   1,   1],
       [ 65,   0, 171, ...,   1,   1,   0]])

In [ ]:
y_test

array([0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0])

#Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
X_train

array([[-0.04759104,  0.96647087,  1.20049844, ..., -1.00379508,
         0.95553309, -0.89901011],
       [ 0.20751626,  0.96647087,  0.4292294 , ..., -1.00379508,
         0.95553309, -0.89901011],
       [ 0.27129309, -1.03469234, -0.34203964, ...,  0.99621927,
        -1.04653624, -0.89901011],
       ...,
       [ 0.90906134, -1.03469234, -0.08494996, ...,  0.99621927,
         0.95553309, -0.89901011],
       [-0.49402882, -1.03469234, -1.57607011, ...,  0.99621927,
        -1.04653624, -0.89901011],
       [-0.55780565, -1.03469234,  0.82343357, ..., -1.00379508,
        -1.04653624,  1.11233454]])

In [ ]:
X_test

array([[-1.38690438, -1.03469234, -0.39345758, ...,  0.99621927,
        -1.04653624, -0.89901011],
       [-0.87668977, -1.03469234, -0.83907969, ...,  0.99621927,
         0.95553309, -0.89901011],
       [ 1.35549912, -1.03469234,  0.84057289, ...,  0.99621927,
         0.95553309,  1.11233454],
       ...,
       [-0.23892152,  0.96647087,  1.32047362, ...,  0.99621927,
         0.95553309, -0.89901011],
       [-1.38690438,  0.96647087,  1.61184193, ..., -1.00379508,
         0.95553309,  1.11233454],
       [ 0.78150769, -1.03469234, -1.33611974, ...,  0.99621927,
         0.95553309, -0.89901011]])

#Training SVM classifier model on training set

In [ ]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)

SVC(random_state=0)

#Predicting Test set result


In [ ]:
y_pred= classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [0 0]]


#Making Confusion Metrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[79  4]
 [ 5 44]]


0.9318181818181818

#Training Naive Bayes Classification model

In [ ]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

#Predicting Test set result

In [ ]:
y_pred= classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]]


#Making Confusion Metrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[81  2]
 [ 7 42]]


0.9318181818181818

In [ ]:
from sklearn.naive_bayes import BernoulliNB
classifier = BernoulliNB()
classifier.fit(X_train, y_train)

BernoulliNB()

In [ ]:
y_pred= classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [0 1]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [1 0]]


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[66 17]
 [ 3 46]]


0.8484848484848485

#Training Decision Tree Classification model

In [ ]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'gini', random_state = 0)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(random_state=0)

#Predicting Test set result

In [ ]:
y_pred= classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]]


#Making Confusion Metrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[83  0]
 [ 0 49]]


1.0

#Training Random Forest Classification model

In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

#Predicting Test set result

In [ ]:
y_pred= classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]]


#Making Confusion Metrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[83  0]
 [ 0 49]]


1.0

In [ ]:
my_dict= {
    "Logistic Regression": 0.8939393939393939,
    "KNN": 0.9015151515151515,
    "SVM": 0.8787878787878788,
    "Naive Bayes (Gaussain)": 0.9318181818181818,
    "Naive Bayes (Bernoulli)": 0.8484848484848485,
    "Decision Tree": 1,
    "Random Forest": 1
}

In [ ]:
Series= pd.Series(my_dict)
Series

Logistic Regression        0.893939
KNN                        0.901515
SVM                        0.878788
Naive Bayes (Gaussain)     0.931818
Naive Bayes (Bernoulli)    0.848485
Decision Tree              1.000000
Random Forest              1.000000
dtype: float64